// Conventional Commits 1.0.0 validator, run by the Lefthook commit-msg hook.
// Rules: whole message ≤ MAX_LENGTH characters; header `type(scope)!: description`;
// description starts lowercase, has no trailing period; blank line before the body.

export const MAX_LENGTH = 150;

export const TYPES = [
  'build',
  'chore',
  'ci',
  'docs',
  'feat',
  'fix',
  'perf',
  'refactor',
  'revert',
  'style',
  'test',
] as const;

const HEADER = new RegExp(`^(${TYPES.join('|')})(\\([a-z0-9-]+\\))?(!)?: (.+)$`);
const SCISSORS = '# ------------------------ >8 ------------------------';

// Drops what git itself discards: comment lines, the scissors section and surrounding blank lines.
export function normalize(raw: string): string {
  const cut = raw.indexOf(SCISSORS);
  const kept = cut === -1 ? raw : raw.slice(0, cut);
  return kept
    .split('\n')
    .filter((line) => !line.startsWith('#'))
    .join('\n')
    .trim();
}

export function validateCommitMessage(raw: string): string[] {
  const message = normalize(raw);
  if (message.length === 0) return ['message is empty'];

  const errors: string[] = [];
  if (message.length > MAX_LENGTH) {
    errors.push(`message has ${message.length} characters; the maximum is ${MAX_LENGTH}`);
  }

  const [header = '', secondLine] = message.split('\n');

  // Messages generated by git itself (`git merge`, `git revert`) only get the length check.
  if (header.startsWith('Merge ') || header.startsWith('Revert "')) return errors;

  const match = HEADER.exec(header);
  if (!match) {
    errors.push(`header must be "type(scope)!: description", type one of: ${TYPES.join(', ')}`);
    return errors;
  }

  const description = match[4] ?? '';
  if (description !== description.trim()) {
    errors.push('description must not start or end with spaces');
  }
  if (/^[A-Z]/.test(description)) errors.push('description must start with a lowercase letter');
  if (description.endsWith('.')) errors.push('description must not end with a period');
  if (secondLine !== undefined && secondLine !== '') {
    errors.push('leave a blank line between the header and the body');
  }

  return errors;
}

if (import.meta.main) {
  const file = Bun.argv[2];
  if (!file) {
    console.error('usage: bun scripts/commit-msg.ts <commit-msg-file>');
    process.exit(2);
  }

  const errors = validateCommitMessage(await Bun.file(file).text());
  if (errors.length > 0) {
    console.error(`✖ Invalid commit message (Conventional Commits, max ${MAX_LENGTH} characters):`);
    for (const error of errors) console.error(`  - ${error}`);
    process.exit(1);
  }
}
